In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("mabel.txt", header=None, encoding='utf8', on_bad_lines='skip')

In [3]:
df

           0                                                  1
0   05/12/19   1:42 pm - Messages to this chat and calls are...
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [4]:
df=df.drop(0)

In [5]:
df.columns=['Date','Chat']

In [6]:
df

        Date                                               Chat
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [7]:
Message=df["Chat"].str.split("-",n=1,expand=True)

In [8]:
Message

             0                                                  1
1     1:42 pm     Mabel Infoziant: Hi this is Mabel we just spoke
2     1:42 pm              Mabel Infoziant: What’s your full name
3     1:42 pm                                 AR❤: Ramisha Rani K
4     1:42 pm                                 Mabel Infoziant: Ok
5     1:42 pm             Mabel Infoziant: ramisharanik@gmail.com
6     1:43 pm                     Mabel Infoziant: Your email Id?
7     1:43 pm                                        AR❤: Yes Mam
8     1:43 pm    Mabel Infoziant: I will send 2 abstracts for ...
9     1:43 pm                                       AR❤: Yeah mam
10    1:43 pm    Mabel Infoziant: Give me the list that u have...
11    1:43 pm    Mabel Infoziant: Send me cbe office address a...
12    1:44 pm    AR❤: Yeah Mam within Evening I will forward y...
13    1:45 pm    AR❤: Tomorrow I have to visit the office.yet ...
14    1:48 pm                                 Mabel Infoziant: ok
15    1:48 pm    Mabel Infoziant: send the details of office l...
16    1:49 pm    AR❤: Sure mam. Soon I will share details with...
17    2:00 pm    AR❤: I have read the Abstract mam. We can do ...
18    2:04 pm    Mabel Infoziant: I think Vignesh has the data...
19    2:04 pm          Mabel Infoziant: I have sent the abstracts
20    2:06 pm                                         AR❤: Ok mam
21    2:07 pm    AR❤: I have read both the abstract mam. We ca...
22    4:44 pm    Mabel Infoziant: Yes we need to ya about amou...
23    4:48 pm                                      AR❤: Sure mam.
24    8:07 pm                              AR❤: Shall I call mam?
25   10:45 pm    Mabel Infoziant: Hi I was at church couldn’t ...
26   11:52 pm                                     AR❤: It's k mam
27   11:55 pm    AR❤: Just to know the tomorrow plan mam.will ...
28   12:09 pm                AR❤: Mam can u send Vignesh number??
29   12:13 pm    Mabel Infoziant: Vignesh ML Infoziant.vcf (fi...
30   12:23 pm           Mabel Infoziant: I was in a meeting sorry
31   12:25 pm                                AR❤: Can I cal u mam
32   12:26 pm    AR❤: Waiting for u r finalization of rates fo...
33   12:26 pm    AR❤: If we finiliaze I can work with full inv...
34   12:28 pm    AR❤: So what ever may be ..if you think your ...
35   12:28 pm                       AR❤: You deleted this message
36   12:29 pm                                 AR❤: Do the needful
37   12:41 pm    Mabel Infoziant: No ma please hold I am in a ...
38   12:42 pm                                 AR❤: Ok mam thank u
39    7:59 am    Mabel Infoziant: Ramisha we need to talk toda...
40    8:00 am    Mabel Infoziant: Be ready to discuss about th...
41    8:55 am                                       AR❤: Okay mam
42    2:26 pm                                 Mabel Infoziant: ok
43    8:22 pm                                AR❤: Mam are u free?
44    8:40 pm    Mabel Infoziant: Am at church can call very l...
45    8:40 pm    AR❤: Kk mam. I will ask Arun brother. Small d...
46    3:09 pm                                         AR❤: Hi mam
47    3:09 pm                               AR❤: Any updates mam?
48    3:11 pm    Mabel Infoziant: U might have to start on the...
49    3:11 pm    Mabel Infoziant: There is one project that go...
50    3:12 pm                                       AR❤: Kk mam👍🏻

In [9]:
df["Time"]=Message[0]
Message1=Message[1].str.split(":",n=1,expand=True)

In [10]:
Message1

                   0                                                  1
1    Mabel Infoziant                     Hi this is Mabel we just spoke
2    Mabel Infoziant                              What’s your full name
3                AR❤                                     Ramisha Rani K
4    Mabel Infoziant                                                 Ok
5    Mabel Infoziant                             ramisharanik@gmail.com
6    Mabel Infoziant                                     Your email Id?
7                AR❤                                            Yes Mam
8    Mabel Infoziant     I will send 2 abstracts for u to start working
9                AR❤                                           Yeah mam
10   Mabel Infoziant                   Give me the list that u have too
11   Mabel Infoziant   Send me cbe office address and phone number I...
12               AR❤    Yeah Mam within Evening I will forward you mam.
13               AR❤   Tomorrow I have to visit the office.yet not I...
14   Mabel Infoziant                                                 ok
15   Mabel Infoziant   send the details of office location once u ge...
16               AR❤   Sure mam. Soon I will share details with you mam
17               AR❤   I have read the Abstract mam. We can do mam. ...
18   Mabel Infoziant   I think Vignesh has the data set will ask him...
19   Mabel Infoziant                          I have sent the abstracts
20               AR❤                                             Ok mam
21               AR❤   I have read both the abstract mam. We can do ...
22   Mabel Infoziant   Yes we need to ya about amount and all other ...
23               AR❤                                          Sure mam.
24               AR❤                                  Shall I call mam?
25   Mabel Infoziant         Hi I was at church couldn’t take your call
26               AR❤                                         It's k mam
27               AR❤   Just to know the tomorrow plan mam.will see t...
28               AR❤                    Mam can u send Vignesh number??
29   Mabel Infoziant           Vignesh ML Infoziant.vcf (file attached)
30   Mabel Infoziant                           I was in a meeting sorry
31               AR❤                                    Can I cal u mam
32               AR❤   Waiting for u r finalization of rates for our...
33               AR❤   If we finiliaze I can work with full involvem...
34               AR❤   So what ever may be ..if you think your are c...
35               AR❤                           You deleted this message
36               AR❤                                     Do the needful
37   Mabel Infoziant   No ma please hold I am in a hot meeting with ...
38               AR❤                                     Ok mam thank u
39   Mabel Infoziant   Ramisha we need to talk today i will call u a...
40   Mabel Infoziant     Be ready to discuss about the ML titles u have
41               AR❤                                           Okay mam
42   Mabel Infoziant                                                 ok
43               AR❤                                    Mam are u free?
44   Mabel Infoziant   Am at church can call very late or tomorrow only
45               AR❤   Kk mam. I will ask Arun brother. Small doubt ...
46               AR❤                                             Hi mam
47               AR❤                                   Any updates mam?
48   Mabel Infoziant     U might have to start on the WhatsApp analysis
49   Mabel Infoziant            There is one project that got committed
50               AR❤                                           Kk mam👍🏻

In [11]:
df["Name"]=Message1[0]

In [12]:
df["Chat"]=Message1[1]

In [13]:
df=df[["Date","Time","Name","Chat"]]
df

,Date,Time,Name,Chat
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K
4,05/12/19,1:42 pm,Mabel Infoziant,Ok
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?
7,05/12/19,1:43 pm,AR❤,Yes Mam
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working
9,05/12/19,1:43 pm,AR❤,Yeah mam
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...
14,05/12/19,1:48 pm,Mabel Infoziant,ok
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts
20,05/12/19,2:06 pm,AR❤,Ok mam
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...
23,05/12/19,4:48 pm,AR❤,Sure mam.
24,05/12/19,8:07 pm,AR❤,Shall I call mam?
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call
26,08/12/19,11:52 pm,AR❤,It's k mam
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached)
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry
31,09/12/19,12:25 pm,AR❤,Can I cal u mam
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...
35,09/12/19,12:28 pm,AR❤,You deleted this message
36,09/12/19,12:29 pm,AR❤,Do the needful
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...
38,09/12/19,12:42 pm,AR❤,Ok mam thank u
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have
41,10/12/19,8:55 am,AR❤,Okay mam
42,12/12/19,2:26 pm,Mabel Infoziant,ok
43,15/12/19,8:22 pm,AR❤,Mam are u free?
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...
46,18/12/19,3:09 pm,AR❤,Hi mam
47,18/12/19,3:09 pm,AR❤,Any updates mam?
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 1 to 50
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    50 non-null     object
 1   Time    50 non-null     object
 2   Name    50 non-null     object
 3   Chat    50 non-null     object
dtypes: object(4)
memory usage: 1.7+ KB

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
tfidf=TfidfVectorizer(max_df=0.95,min_df=2,stop_words='english')
dtm=tfidf.fit_transform(df["Chat"])

In [17]:
from sklearn.decomposition import LatentDirichletAllocation

lda = LatentDirichletAllocation(n_components=5, random_state=42)
lda.fit(dtm)

LatentDirichletAllocation(n_components=5, random_state=42)

In [ ]:

#This improves topic separation


#custom_stopwords = ['yes','ok','hi','mam','kk','yeah','just']

##texts = [
 #   [word for word in str(text).split() if word not in custom_stopwords]
  #  for text in df["Chat"]
#]

In [18]:
for index, topic in enumerate(lda.components_):
    results = [tfidf.get_feature_names_out()[i] for i in topic.argsort()[-10:]]
    print(f"Topic {index}: ", results)

Topic 0:  ['number', 'need', 'yes', 'hi', 'just', 'office', 'send', 'details', 'vignesh', 'ml']
Topic 1:  ['meeting', 'soon', 'ramisha', 'number', 'office', 'students', 'phone', 'yes', 'need', 'ok']
Topic 2:  ['ask', 'project', 'think', 'read', 'abstract', 'sure', 'kk', 'finiliaze', 'yeah', 'mam']
Topic 3:  ['soon', 'ask', 'mam', 'office', 'just', 'know', 'church', 'meeting', 'project', 'tomorrow']
Topic 4:  ['details', 'yes', 'ask', 'mam', 'send', 'church', 'ramisha', 'hi', 'start', 'abstracts']

In [19]:
topic_results=lda.transform(dtm)
df["Topic"]=topic_results.argmax(axis=1)

C:\Users\gnana\AppData\Local\Temp\ipykernel_16760\2728423132.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Topic"]=topic_results.argmax(axis=1)

In [20]:
df

,Date,Time,Name,Chat,Topic
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke,0
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name,0
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K,4
4,05/12/19,1:42 pm,Mabel Infoziant,Ok,1
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com,0
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?,0
7,05/12/19,1:43 pm,AR❤,Yes Mam,1
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working,4
9,05/12/19,1:43 pm,AR❤,Yeah mam,2
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too,0
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...,1
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.,2
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...,0
14,05/12/19,1:48 pm,Mabel Infoziant,ok,1
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...,1
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam,2
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...,2
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...,0
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts,4
20,05/12/19,2:06 pm,AR❤,Ok mam,1
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...,2
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...,0
23,05/12/19,4:48 pm,AR❤,Sure mam.,2
24,05/12/19,8:07 pm,AR❤,Shall I call mam?,2
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call,4
26,08/12/19,11:52 pm,AR❤,It's k mam,2
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...,3
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??,0
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached),0
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry,3
31,09/12/19,12:25 pm,AR❤,Can I cal u mam,2
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...,0
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...,2
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...,2
35,09/12/19,12:28 pm,AR❤,You deleted this message,0
36,09/12/19,12:29 pm,AR❤,Do the needful,0
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...,1
38,09/12/19,12:42 pm,AR❤,Ok mam thank u,1
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...,1
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have,0
41,10/12/19,8:55 am,AR❤,Okay mam,2
42,12/12/19,2:26 pm,Mabel Infoziant,ok,1
43,15/12/19,8:22 pm,AR❤,Mam are u free?,2
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only,3
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...,2
46,18/12/19,3:09 pm,AR❤,Hi mam,4
47,18/12/19,3:09 pm,AR❤,Any updates mam?,2
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis,4
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed,3
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻,2

In [21]:
df["Topic"].value_counts()

Topic
2    16
0    14
1    10
4     6
3     4
Name: count, dtype: int64

In [22]:
pip install gensim

Requirement already satisfied: gensim in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from gensim) (2.2.5)
Requirement already satisfied: scipy>=1.7.0 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from gensim) (1.15.3)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Note: you may need to restart the kernel to use updated packages.

In [25]:
from gensim.corpora import Dictionary

dictionary = Dictionary(texts)
from gensim.models import CoherenceModel
from gensim.corpora import Dictionary
from sklearn.decomposition import LatentDirichletAllocation

# Step 1: Prepare texts
texts = [str(text).split() for text in df["Chat"]]

# Step 2: Create dictionary
dictionary = Dictionary(texts)

# Step 3: Train LDA and calculate coherence
coherence_scores = []

for k in range(2, 10):
    lda = LatentDirichletAllocation(n_components=k, random_state=42)
    lda.fit(dtm)

    # Extract topics (IMPORTANT for sklearn LDA)
    feature_names = tfidf.get_feature_names_out()
    topics = [
        [feature_names[i] for i in topic.argsort()[-10:]]
        for topic in lda.components_
    ]

    coherence_model = CoherenceModel(
        topics=topics,
        texts=texts,
        dictionary=dictionary,
        coherence='c_v'
    )

    coherence_scores.append(coherence_model.get_coherence())

print(coherence_scores)

[np.float64(0.4127390811941356), np.float64(0.4693313344482879), np.float64(0.43576970000139026), np.float64(0.47593641614061094), np.float64(0.4569392708805728), np.float64(0.4919317125155546), np.float64(0.4653440797060319), np.float64(0.44173616074318894)]

In [ ]:
#Score	Meaning
#> 0.5	Good
#0.3 – 0.5	Average
#< 0.3	Poor